# Set a longer timeout. The default is 10m (600s).
# GKE apply can take 15-20 minutes, so 20m or more is safer.
timeout: 1500s  # 25 minutes

steps:
  # -----------------------------------------------------------------
  # STEP 1: TERRAFORM INIT
  # -----------------------------------------------------------------
  # Use a pinned, stable version.
  - name: 'hashicorp/terraform:1.13.4'
    id: 'Terraform Init'
    args:
      - 'init'
    # This is the most important fix:
    # Run the command INSIDE the environment folder.
    dir: ${_TERRAFORM_DIR}

  # -----------------------------------------------------------------
  # STEP 2: TERRAFORM PLAN
  # -----------------------------------------------------------------
  # The 'tfplan' file will be created inside the 'dir' folder.
  - name: 'hashicorp/terraform:1.8.5'
    id: 'Terraform Plan'
    args: ['plan', '-out=tfplan']
    dir: ${_TERRAFORM_DIR}

  # -----------------------------------------------------------------
  # STEP 3: TERRAFORM APPLY
  # -----------------------------------------------------------------
  # Applies the 'tfplan' from the 'dir' folder.
  - name: 'hashicorp/terraform:1.8.5'
    id: 'Terraform Apply'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: ${_TERRAFORM_DIR}

# Optional: Save the 'tfplan' file for auditing
artifacts:
  objects:
    # !! CHANGE THIS and select your bucket
    location: 'gs://meli-tf/artifacts/'
    
    # We must specify the full path to the plan file
    paths: ['${_TERRAFORM_DIR}/tfplan']

# Default value for the variable passed by the Trigger
substitutions:
  _TERRAFORM_DIR: 'terraform/environments/luisenv'